# Generated by Django 3.1.7 on 2022-02-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20220202_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthday_wishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
