# Generated by Django 3.1.7 on 2022-02-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_auto_20220203_0402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birthday_wishes',
            new_name='BirthdayWishes',
        ),
    ]
